version: '3.3'

services:

  synchronizer:
    container_name: "synchronizer"
    build:
      context: ./services/synchronizer
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongo_db
    networks:
      - samplenetwork

  sqlite3:
    image: nouchka/sqlite3:latest
    container_name: "sqlite3"
    ports:
      - "27021:27021"
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
    networks:
      - samplenetwork

networks:
  samplenetwork:
    driver: bridge