version: '3.3'

services:

  synchronizer:
    container_name: "synchronizer"
    build:
      context: ./services/synchronizer
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      - FLASK_ENV=development
    depends_on:
      - postgresql
    networks:
      - samplenetwork

  postgresql:
    image: postgres
    container_name: "postgresql"
    ports:
      - "27021:27021"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: admin
    networks:
      - samplenetwork

networks:
  samplenetwork:
    driver: bridge