version: '3.3'

services:

  synchronizer:
    container_name: "synchronizer"
    build:
      context: ./services/synchronizer
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongo_db_qabox
    networks:
      - samplenetwork

  mongo_db_qabox:
    image: mongo:4.0.11
    container_name: "mongo_db_qabox"
    ports:
      - "27021:27021"
    command: mongod --bind_ip_all --port 27021 --smallfiles --logpath=/dev/null # --quiet
    networks:
      - samplenetwork

networks:
  samplenetwork:
    driver: bridge
